### ISSUE TITLE
command crawl start results in TypeError

### ISSUE THREAD

**Issue by nvanderperren** [webrecorder/browsertrix-old#49]
With `browsertrix crawl start eb6a588b7aae` I expected to start the crawl with id `eb6a588b7aae` that I had stopped earlier. I recieved following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/browsertrix", line 33, in <module>
    sys.exit(load_entry_point('browsertrix-cli==0.1.0.dev0', 'console_scripts', 'browsertrix')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: start_crawl() missing 3 required positional arguments: 'browser', 'headless', and 'behavior_time'
```

Did I do something wrong? How do I restart a crawl?

**Comment by nvanderperren** [comment]
I can restart it with the UI. There is only an issue for this command in the CLI.
